/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KullaniciTasarimi;

import java.awt.Color;

/**
 *
 * @author merve
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
        GirisEkraniPaneli.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GirisEkraniPaneli = new javax.swing.JPanel();
        OrendaBankText = new javax.swing.JLabel();
        HoşGeldinizText = new javax.swing.JLabel();
        GirisButon = new javax.swing.JButton();
        BasvurButon = new javax.swing.JButton();
        BasvurText = new javax.swing.JLabel();
        TCNOText = new javax.swing.JTextField();
        SifreText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orenda Bank Giris Ekranı");

        GirisEkraniPaneli.setBackground(new java.awt.Color(204, 204, 255));

        OrendaBankText.setFont(new java.awt.Font("Forte", 1, 40)); // NOI18N
        OrendaBankText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrendaBankText.setText("OrendaBank");

        HoşGeldinizText.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        HoşGeldinizText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HoşGeldinizText.setText("Hoş Geldiniz...");

        GirisButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GirisButon.setText("GİRİŞ");
        GirisButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GirisButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GirisButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GirisButonMouseExited(evt);
            }
        });

        BasvurButon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BasvurButon.setText("Hemen BAŞVUR");
        BasvurButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BasvurButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BasvurButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BasvurButonMouseExited(evt);
            }
        });

        BasvurText.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BasvurText.setText("Müşterimiz olmak için");

        TCNOText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TCNOText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCNOTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GirisEkraniPaneliLayout = new javax.swing.GroupLayout(GirisEkraniPaneli);
        GirisEkraniPaneli.setLayout(GirisEkraniPaneliLayout);
        GirisEkraniPaneliLayout.setHorizontalGroup(
            GirisEkraniPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GirisEkraniPaneliLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(GirisEkraniPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(OrendaBankText)
                    .addComponent(HoşGeldinizText)
                    .addComponent(TCNOText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GirisButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BasvurText)
                    .addComponent(BasvurButon))
                .addGap(77, 77, 77))
        );

        GirisEkraniPaneliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SifreText, TCNOText});

        GirisEkraniPaneliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BasvurButon, GirisButon});

        GirisEkraniPaneliLayout.setVerticalGroup(
            GirisEkraniPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GirisEkraniPaneliLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(OrendaBankText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoşGeldinizText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(TCNOText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SifreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GirisButon)
                .addGap(70, 70, 70)
                .addComponent(BasvurText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BasvurButon)
                .addGap(30, 30, 30))
        );

        GirisEkraniPaneliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SifreText, TCNOText});

        GirisEkraniPaneliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BasvurButon, GirisButon});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GirisEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GirisEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCNOTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCNOTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCNOTextActionPerformed
    private Color orijinalBgColor;
    
    private void GirisButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GirisButonMouseEntered
        orijinalBgColor = GirisButon.getBackground();
        GirisButon.setBackground(Color.GRAY);
    }//GEN-LAST:event_GirisButonMouseEntered

    private void GirisButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GirisButonMouseExited
        GirisButon.setBackground(orijinalBgColor);
    }//GEN-LAST:event_GirisButonMouseExited
    private Color orijinalBgColor2;
    private void BasvurButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BasvurButonMouseEntered
        orijinalBgColor2 = BasvurButon.getBackground();
        BasvurButon.setBackground(Color.GRAY);
    }//GEN-LAST:event_BasvurButonMouseEntered

    private void BasvurButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BasvurButonMouseExited
        BasvurButon.setBackground(orijinalBgColor2);
    }//GEN-LAST:event_BasvurButonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasvurButon;
    private javax.swing.JLabel BasvurText;
    private javax.swing.JButton GirisButon;
    private javax.swing.JPanel GirisEkraniPaneli;
    private javax.swing.JLabel HoşGeldinizText;
    private javax.swing.JLabel OrendaBankText;
    private javax.swing.JPasswordField SifreText;
    private javax.swing.JTextField TCNOText;
    // End of variables declaration//GEN-END:variables
}
